all :
#	gfortran gsm.f -ffixed-line-length-100 -o skybkg_angelica
	gfortran gsm_range.f -ffixed-line-length-200 -o skybkg_angelica_range
	cp skybkg_angelica_range $(BIGHORNS)/bin/		
	
clean :
	rm -f skybkg_angelica 
			
